trigger:
  - main

pr: none

pool:
  vmImage: 'ubuntu-20.04'

stages:
- stage: check_validation
  displayName: Check validation
  jobs:
  - job: waitForValidation
    pool: server
    displayName: Manual Validation
    steps:   
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'sharmasakshi1@seasiainfotech.com'
        instructions: 'Please validate the build configuration and resume'

- stage: code_check
  displayName: Code Check
  jobs:
  - job: publishreport
    displayName: Publish Report
    steps:
    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: 'coverage/clover.xml'

- stage: BUILD
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
        addToPath: true
        architecture: 'x64'
    
    - bash: |
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: 'Install Dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive Files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: drop

- stage: Deploy
  displayName: Deploy Stage with Approval
  dependsOn: BUILD
  jobs:
  - deployment: DeployJob
    displayName: Deployment Job
    environment: DEV  # Define the environment
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: |
              echo "Deploying application..."
            displayName: 'Deploy Application'
